version: '3.1'

services:
  mongo:
    image: mongo:5.0
    container_name: db_cloud
    restart: always
    volumes:
      - ~/Documents/Development/databases/db_cloud:/data/db
    ports:
      - '27027:27017'
    environment:
      MONGO_INITDB_DATABASE: cloud
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: xLx210ET5EMkD
