version: '3.9'

services:
  db:
    image: postgres:16.2
    container_name: db_cloud
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5413:5432"
    environment:
      POSTGRES_DB: db_cloud
      POSTGRES_USER: admin_cloud
      POSTGRES_PASSWORD: q2w3e13
